permalink: pretty
baseurl: "/"

backend:
  name: github
  repo: pomme-health/pomme-health-website

media_folder: "images/uploads"
display_url: "/"

editor:
  preview: false

collections:
  - label: "Website Settings"
    name: "website-settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Copyright"
            name: "copyright"
            widget: "string"
          - label: "Social Media"
            name: "socialMedia"
            widget: "object"
            fields:
              - label: "Linkedin"
                name: "linkedin"
                widget: "string"
              - label: "Twitter"
                name: "twitter"
                widget: "string"
              - label: "Instagram"
                name: "instagram"
                widget: "string"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "heroBanner"
            widget: "object"
            required: false
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "buttonText"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
          - label: "Cards Section Title"
            name: "sectionTitle"
            widget: "string"
          - label: "Home Cards"
            name: "homeCards"
            widget: "list"
            fields:
              - label: "Icon"
                name: "icon"
                widget: "image"
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
          - label: "Home Sections"
            name: "homeSections"
            widget: "list"
            required: false
            fields:
              - label: "Leading Text"
                name: "leadingText"
                widget: "string"
              - label: "Title"
                name: "mainSectionHeader"
                widget: "string"
              - label: "Text"
                name: "mainSectionText"
                widget: "string"
              - label: "Button Text"
                name: "sectionButton"
                widget: "string"
              - label: "Button Link"
                name: "buttonLink"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
          - label: "Get in Touch"
            name: "getInTouch"
            widget: "object"
            required: false
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
      - label: "POMMe Platform"
        name: "pomme-platform"
        file: "_data/platform.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Text"
                name: "text"
          - label: "Platform Sections"
            name: "platformSections"
            widget: "list"
            fields:
              - label: "Title"
                name: "mainSectionHeader"
                widget: "string"
              - label: "Text"
                name: "mainSectionText"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
      - label: "Health Care Professionals"
        name: "healthcare-professionals"
        file: "_data/healthcare-professionals.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Text"
                name: "text"
                widget: "string"
          - label: "Professionals Sections"
            name: "professionalsSections"
            widget: "list"
            fields:
              - label: "Section Text"
                name: "text"
                widget: "markdown"
              - label: "Section Image"
                name: "image"
                widget: "image"
          - label: "Push"
            name: "pushClass"
            widget: "hidden"
          - label: "Pull"
            name: "pullClass"
            widget: "hidden"
      - label: "Patients and Family"
        name: "patients-family"
        file: "_data/patients-family.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Text"
                name: "text"
          - label: "Patient Section"
            name: "patientsSections"
            widget: "list"
            fields:
              - label: "Section Text"
                name: "text"
                widget: "markdown"
              - label: "Section Image"
                name: "image"
                widget: "image"
      - label: "Health Care Managers"
        name: "healthcare-managers"
        file: "_data/healthcare-managers.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Text"
                name: "text"
          - label: "Managers Section"
            name: "managersSections"
            widget: "list"
            fields:
              - label: "Section Text"
                name: "text"
                widget: "markdown"
              - label: "Section Image"
                name: "image"
                widget: "image"
      - label: "Blog"
        name: "blog"
        file: "_data/blog.yml"
        fields:
          - label: "Blog Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Text"
                name: "text"
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "History"
            name: "history"
            widget: "object"
            fields:
              - label: "History"
                name: "text"
                widget: "markdown"
          - label: "Mission"
            name: "mission"
            widget: "object"
            fields:
              - label: "Mission Header"
                name: "missionHeader"
                widget: "string"
              - label: "Mission Text"
                name: "missionText"
                widget: "string"
          - label: "Leadership"
            name: "leadership"
            widget: "list"
            fields:
              - label: "Person Name"
                name: "personName"
                widget: "string"
              - label: "Person Text"
                name: "leaderText"
                widget: "string"
          - label: "In the News"
            name: "inTheNews"
            widget: "list"
            fields:
              - label: "News Title"
                name: "newsTitle"
                widget: "string"
              - label: "News Description"
                name: "newsDescription"
                widget: "string"
              - label: "News Image"
                name: "newsImage"
                widget: "image"
      - label: "Comprehensive"
        name: "comprehensive"
        file: comprehensive.md
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Collaborative"
        name: "collaborative"
        file: collaborative.md
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Continuous"
        name: "continuous"
        file: continuous.md
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Customizable"
        name: "customizable"
        file: customizable.md
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Contact"
        name: "contactPage"
        file: "_data/contact.yml"
        fields:
          - label: "Contact Information"
            name: "contactInformation"
            widget: "object"
            fields:
              - label: "Email Address"
                name: "contactEmail"
                widget: "string"
              - label: "Telephone Number"
                name: "contactTel"
                widget: "string"
          - label: "Investors"
            name: "investors"
            widget: "object"
            fields:
              - label: "Investors Text"
                name: "text"
                widget: "markdown"
          - label: "Careers"
            name: "careers"
            widget: "object"
            fields:
              - label: "Careers Image"
                name: "careersImage"
                widget: "image"
              - label: "Careers Text"
                name: "careersText"
                widget: "string"
  - label: "Blog Posts"
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
